[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
description = "SPL Token Lending CLI"
edition = "2018"
homepage = "https://spl.solana.com/token-lending"
license = "Apache-2.0"
name = "spl-token-lending-cli"
repository = "https://github.com/solana-labs/solana-program-library"
version = "0.1.0"

[dependencies]
clap = "3.0.13"
solana-clap-utils = "1.8.14"
solana-cli-config = "1.8.14"
solana-client = "1.8.14"
solana-logger = "1.8.14"
solana-sdk = "1.8.14"
solana-program = "1.8.14"
spl-token-lending = { path="../program", features = [ "no-entrypoint" ] }
spl-token = "3.3.0"

[[bin]]
name = "spl-token-lending"
path = "src/main.rs"
